# Generated by Django 5.0.6 on 2024-06-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, unique=True, verbose_name='Titre')),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('publication_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-publication_date',),
            },
        ),
    ]
