# Generated by Django 5.0.6 on 2024-06-24 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-publication_date',), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
